version: '3.4'

services:
  db:
    image: mysql_flask
    env_file: 
      - ./config/db.env
    restart: always
    ports:
      - 3308:3306
    networks:
      - rede_flask
  
  backend:
    depends_on:
      - db
    image: flask_host
    ports:
      - 5000:5000
    restart: always
    networks:
      - rede_flask

networks:
  rede_flask:
    driver: bridge
    